<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="wjn" name="yuansheng_houtai_action.chanpinTest" tests="10" failures="1" timestamp="12 Dec 2017 07:30:35 GMT" time="234.712" errors="0">
  <testcase name="testfujian" time="19.028" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testbuju_s" time="24.137" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testchanpin" time="51.834" classname="yuansheng_houtai_action.chanpinTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yuansheng_houtai_action.chanpinTest.testchanpin(chanpinTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
    </failure>
  </testcase> <!-- testchanpin -->
  <testcase name="testfanhui" time="23.808" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testbuju" time="19.848" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testtupian" time="19.034" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testsousuo" time="19.447" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testbianji" time="19.389" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testgdshanc" time="21.417" classname="yuansheng_houtai_action.chanpinTest"/>
  <testcase name="testgengduo" time="16.770" classname="yuansheng_houtai_action.chanpinTest"/>
</testsuite> <!-- yuansheng_houtai_action.chanpinTest -->
